#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Rio GitHub release setup"

stage "GitHub — command-line access"
say "The next stages write signing and notarization values to this repository's GitHub Actions secrets."
if ! command -v gh >/dev/null 2>&1; then
  warn "GitHub CLI (gh) is not installed. Install it from https://cli.github.com/, then re-run this wizard."
else
  if ! gh auth status >/dev/null 2>&1; then
    step "Run 'gh auth login' and authenticate to the GitHub account that owns this repository."
    pause "After gh auth login succeeds, press Enter"
  fi
  if gh auth status >/dev/null 2>&1; then
    repo_name=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
    note "GitHub repository: $repo_name"
  else
    warn "gh is still unauthenticated; secret writes will be skipped and listed at the end."
  fi
fi
pause "Press Enter to continue"

stage "Apple — Developer ID certificate"
say "Create or use a Developer ID Application certificate, then export it as a password-protected .p12 file."
open_url "https://developer.apple.com/account/resources/certificates/list"
step "Create a Developer ID Application certificate if you do not already have one."
step "In Keychain Access, export that certificate together with its private key as a .p12 file."
ask CERTIFICATE_PATH "Path to the exported .p12 file:"
if [[ ! -f "$CERTIFICATE_PATH" ]]; then
  warn "Certificate file not found: $CERTIFICATE_PATH"
  exit 1
fi
ask_secret CERTIFICATE_PASSWORD "Password used when exporting the .p12 file:"
if confirm "Upload this certificate and password to GitHub Actions secrets?"; then
  set_secret APPLE_DEVELOPER_ID_CERTIFICATE_BASE64 "$(base64 < "$CERTIFICATE_PATH" | tr -d '\n')"
  set_secret APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD "$CERTIFICATE_PASSWORD"
fi

stage "Apple — Developer ID provisioning profile"
say "Create a distribution profile for Rio's existing App ID com.rubensmelo.rio and download it."
open_url "https://developer.apple.com/account/resources/profiles/list"
step "Create the macOS Developer ID/distribution profile type offered for App ID com.rubensmelo.rio."
step "Download the resulting .provisionprofile file."
ask PROFILE_PATH "Path to the downloaded provisioning profile:"
if [[ ! -f "$PROFILE_PATH" ]]; then
  warn "Provisioning profile not found: $PROFILE_PATH"
  exit 1
fi
if confirm "Upload this provisioning profile to GitHub Actions?"; then
  set_secret APPLE_PROVISIONING_PROFILE_BASE64 "$(base64 < "$PROFILE_PATH" | tr -d '\n')"
fi

stage "Apple — notarization API key"
say "Create an App Store Connect API key used only by GitHub Actions to submit the DMG for notarization."
open_url "https://appstoreconnect.apple.com/access/api"
step "Create a team API key with the role Apple documents for notarization, then download the .p8 file."
step "Copy the Key ID and Issuer ID; the .p8 file is available only at download time."
ask APPLE_NOTARY_KEY_ID "App Store Connect API Key ID:"
ask APPLE_NOTARY_ISSUER_ID "App Store Connect Issuer ID:"
ask NOTARY_PRIVATE_KEY_PATH "Path to the downloaded .p8 file:"
if [[ ! -f "$NOTARY_PRIVATE_KEY_PATH" ]]; then
  warn "Notarization key file not found: $NOTARY_PRIVATE_KEY_PATH"
  exit 1
fi
if confirm "Upload the notarization credentials to GitHub Actions?"; then
  set_secret APPLE_NOTARY_KEY_ID "$APPLE_NOTARY_KEY_ID"
  set_secret APPLE_NOTARY_ISSUER_ID "$APPLE_NOTARY_ISSUER_ID"
  set_secret APPLE_NOTARY_PRIVATE_KEY_BASE64 "$(base64 < "$NOTARY_PRIVATE_KEY_PATH" | tr -d '\n')"
fi

stage "GitHub — Apple team variable"
say "The Team ID is public build metadata, so Rio stores it as a GitHub Actions variable rather than a secret."
open_url "https://developer.apple.com/account"
step "Copy the Team ID shown in your Apple Developer account membership details."
ask APPLE_TEAM_ID "Apple Team ID:"
set_var APPLE_TEAM_ID "$APPLE_TEAM_ID"
note "After setup, push a tag such as v1.0.0 to start the release workflow."

finish
